/*\n  # Migration Multi-Tenant - Partie 1 : Table Agencies (Version 3)\n\n  1. Nouvelle table\n    - agencies : Agences immobilières / Bailleurs individuels\n  \n  2. Modifications\n    - user_profiles.agency_id : Lien vers l'agence\n    - Tables métier.agency_id : Isolation multi-tenant\n  \n  3. Sécurité\n    - RLS activé avec politiques par agence\n*/\n\n-- Créer table agencies SANS RLS d'abord\nCREATE TABLE IF NOT EXISTS agencies (\n  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),\n  name text NOT NULL,\n  ninea text,\n  address text,\n  phone text NOT NULL,\n  email text NOT NULL,\n  website text,\n  logo_url text,\n  plan text DEFAULT 'basic' CHECK (plan IN ('basic', 'pro', 'enterprise')),\n  status text DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'trial', 'cancelled')),\n  trial_ends_at timestamptz,\n  is_bailleur_account boolean DEFAULT false,\n  created_at timestamptz DEFAULT now(),\n  updated_at timestamptz DEFAULT now()\n);
\n\n-- Index\nCREATE INDEX IF NOT EXISTS idx_agencies_status ON agencies(status);
\nCREATE INDEX IF NOT EXISTS idx_agencies_plan ON agencies(plan);
\n\n-- Trigger pour updated_at\nDROP TRIGGER IF EXISTS update_agencies_updated_at ON agencies;
\nCREATE TRIGGER update_agencies_updated_at\n  BEFORE UPDATE ON agencies\n  FOR EACH ROW\n  EXECUTE FUNCTION update_updated_at_column();
\n\n-- Ajouter agency_id à user_profiles\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'user_profiles' AND column_name = 'agency_id'\n  ) THEN\n    ALTER TABLE user_profiles ADD COLUMN agency_id uuid REFERENCES agencies(id);
\n    CREATE INDEX idx_user_profiles_agency_id ON user_profiles(agency_id);
\n  END IF;
\nEND $$;
\n\n-- Maintenant activer RLS et créer les politiques\nALTER TABLE agencies ENABLE ROW LEVEL SECURITY;
\n\n-- Politique : Users peuvent voir leur propre agence\nDROP POLICY IF EXISTS "Users can view own agency" ON agencies;
\nCREATE POLICY "Users can view own agency"\n  ON agencies FOR SELECT\n  TO authenticated\n  USING (\n    id IN (\n      SELECT agency_id FROM user_profiles WHERE id = auth.uid()\n    )\n  );
\n\n-- Politique : Admins peuvent mettre à jour leur agence\nDROP POLICY IF EXISTS "Admins can update own agency" ON agencies;
\nCREATE POLICY "Admins can update own agency"\n  ON agencies FOR UPDATE\n  TO authenticated\n  USING (\n    id IN (\n      SELECT agency_id FROM user_profiles\n      WHERE id = auth.uid() AND role = 'admin'\n    )\n  )\n  WITH CHECK (\n    id IN (\n      SELECT agency_id FROM user_profiles\n      WHERE id = auth.uid() AND role = 'admin'\n    )\n  );
\n\n-- Ajouter agency_id à agency_settings\nDO $$\nBEGIN\n  IF NOT EXISTS (\n    SELECT 1 FROM information_schema.columns\n    WHERE table_name = 'agency_settings' AND column_name = 'agency_id'\n  ) THEN\n    ALTER TABLE agency_settings ADD COLUMN agency_id uuid REFERENCES agencies(id);
\n    CREATE INDEX idx_agency_settings_agency_id ON agency_settings(agency_id);
\n  END IF;
\nEND $$;
\n\n-- Ajouter agency_id à toutes les tables métier\nDO $$\nDECLARE\n  tbl_name text;
\nBEGIN\n  FOR tbl_name IN\n    SELECT unnest(ARRAY[\n      'bailleurs', 'immeubles', 'unites', 'locataires',\n      'contrats', 'paiements', 'depenses', 'audit_logs'\n    ])\n  LOOP\n    IF NOT EXISTS (\n      SELECT 1 FROM information_schema.columns\n      WHERE table_schema = 'public'\n      AND table_name = tbl_name\n      AND column_name = 'agency_id'\n    ) THEN\n      EXECUTE format('ALTER TABLE %I ADD COLUMN agency_id uuid REFERENCES agencies(id)', tbl_name);
\n      EXECUTE format('CREATE INDEX idx_%I_agency_id ON %I(agency_id)', tbl_name, tbl_name);
\n    END IF;
\n  END LOOP;
\nEND $$;
;
