alter table public.bailleurs
  add column if not exists is_demo_data boolean not null default false;

alter table public.immeubles
  add column if not exists is_demo_data boolean not null default false;

alter table public.unites
  add column if not exists is_demo_data boolean not null default false;

alter table public.locataires
  add column if not exists is_demo_data boolean not null default false;

alter table public.contrats
  add column if not exists is_demo_data boolean not null default false;

alter table public.paiements
  add column if not exists is_demo_data boolean not null default false;

create index if not exists idx_bailleurs_demo_data
  on public.bailleurs (agency_id, is_demo_data)
  where is_demo_data = true;

create index if not exists idx_immeubles_demo_data
  on public.immeubles (agency_id, is_demo_data)
  where is_demo_data = true;

create index if not exists idx_unites_demo_data
  on public.unites (agency_id, is_demo_data)
  where is_demo_data = true;

create index if not exists idx_locataires_demo_data
  on public.locataires (agency_id, is_demo_data)
  where is_demo_data = true;

create index if not exists idx_contrats_demo_data
  on public.contrats (agency_id, is_demo_data)
  where is_demo_data = true;

create index if not exists idx_paiements_demo_data
  on public.paiements (agency_id, is_demo_data)
  where is_demo_data = true;

comment on column public.bailleurs.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';
comment on column public.immeubles.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';
comment on column public.unites.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';
comment on column public.locataires.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';
comment on column public.contrats.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';
comment on column public.paiements.is_demo_data is
  'Marks sample data generated by Samay Keur so it can be safely reset without touching user data.';

create or replace function public.reset_demo_data(p_agency_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_deleted_revenus integer := 0;
  v_deleted_paiements integer := 0;
  v_deleted_contrats integer := 0;
  v_deleted_locataires integer := 0;
  v_deleted_unites integer := 0;
  v_deleted_immeubles integer := 0;
  v_deleted_bailleurs integer := 0;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not exists (
    select 1
    from public.user_profiles up
    where up.id = auth.uid()
      and up.agency_id = p_agency_id
      and coalesce(up.actif, true) = true
  ) then
    raise exception 'Access denied for this agency';
  end if;

  delete from public.revenus
  where agency_id = p_agency_id
    and paiement_id in (
      select id from public.paiements
      where agency_id = p_agency_id and is_demo_data = true
    );
  get diagnostics v_deleted_revenus = row_count;

  delete from public.paiements
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_paiements = row_count;

  delete from public.contrats
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_contrats = row_count;

  delete from public.locataires
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_locataires = row_count;

  delete from public.unites
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_unites = row_count;

  delete from public.immeubles
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_immeubles = row_count;

  delete from public.bailleurs
  where agency_id = p_agency_id
    and is_demo_data = true;
  get diagnostics v_deleted_bailleurs = row_count;

  update public.agencies
  set demo_data_loaded = false
  where id = p_agency_id;

  return jsonb_build_object(
    'revenus', v_deleted_revenus,
    'paiements', v_deleted_paiements,
    'contrats', v_deleted_contrats,
    'locataires', v_deleted_locataires,
    'unites', v_deleted_unites,
    'immeubles', v_deleted_immeubles,
    'bailleurs', v_deleted_bailleurs
  );
end;
$$;

grant execute on function public.reset_demo_data(uuid) to authenticated;
